#!/usr/bin/env python3
import os,json,hashlib,requests,qrcode,re
from datetime import datetime

class IPTVAutoUpdater:
    def __init__(self, repo_owner='ziizidavid', repo_name='VSA', branch='main'):
        self.repo_owner=repo_owner; self.repo_name=repo_name; self.branch=branch
        self.iptv_file='IPtv'
        self.raw_url=f'https://raw.githubusercontent.com/{repo_owner}/{repo_name}/{branch}/{self.iptv_file}'
        self.github_url=f'https://github.com/{repo_owner}/{repo_name}/blob/{branch}/{self.iptv_file}'
        self.external_source='https://raw.githubusercontent.com/doms9/iptv/refs/heads/default/M3U8/events.m3u8'

    def fetch_external_content(self):
        try:
            r=requests.get(self.external_source,timeout=10); r.raise_for_status()
            return self.filter_external_content(r.text)
        except Exception:
            return None

    def filter_external_content(self, content):
        lines=content.splitlines()
        out=['# --- BEGIN AUTOGENERATED doms9/events.m3u8 (SOCCER ONLY) ---']
        keep=['football','soccer','fifa','world cup','piala dunia','uefa','champions','premier league','la liga','serie a','bundesliga','copa america','euro','afc']
        remove=['cricket','baseball','mlb','nfl','nhl','rugby','golf','tennis']
        i=0
        while i < len(lines):
            line=lines[i]
            if line.startswith('#EXTINF'):
                block=[line]
                j=i+1
                while j < len(lines) and not lines[j].startswith('#EXTINF'):
                    block.append(lines[j]); j+=1
                text=' '.join(block).lower()
                if any(x in text for x in remove):
                    i=j; continue
                if any(x in text for x in keep):
                    block[0]=re.sub(r'group-title="[^"]*"','group-title="EVENT"',block[0])
                    out.extend(block); out.append('')
                i=j
            else:
                i+=1
        return '\n'.join(out)

    def read_existing_content(self):
        return open(self.iptv_file,'r',encoding='utf-8').read() if os.path.exists(self.iptv_file) else None

    def find_insertion_point(self, content):
        marker='http://103.148.44.38:8000/play/a05u/index.m3u8'
        return content.find(marker)+len(marker) if marker in content else len(content)

    def update_iptv_file(self, external_content):
        existing=self.read_existing_content()
        if not existing or not external_content: return False
        insert_pos=self.find_insertion_point(existing)
        updated_content=existing[:insert_pos]+'\n'+external_content
        with open(self.iptv_file,'w',encoding='utf-8') as f: f.write(updated_content)
        return True

    def generate_hash(self): return hashlib.md5(f'{self.raw_url}{datetime.now().isoformat()}'.encode()).hexdigest()[:8]
    def create_links(self):
        uid=self.generate_hash();
        return {'raw_url':self.raw_url,'github_url':self.github_url,'unique_id':uid,'timestamp':datetime.now().isoformat(),'external_source':self.external_source,'formats':{'raw_direct':self.raw_url,'raw_with_cache_bust':f'{self.raw_url}?t={uid}','github_web':self.github_url,'github_raw':f'https://raw.githubusercontent.com/{self.repo_owner}/{self.repo_name}/{self.branch}/{self.iptv_file}?cache={uid}'}}

    def generate_qr_code(self,url,output_path='qrcodes/iptv_playlist_qr.png'):
        pass
    def save_links_json(self,output_path='links_generated.json'):
        links=self.create_links(); open(output_path,'w').write(json.dumps(links,indent=2)); return links
    def display_links(self,links): pass
    def run(self):
        ext=self.fetch_external_content()
        if ext: self.update_iptv_file(ext)
        self.save_links_json('links_generated.json')

def main(): IPTVAutoUpdater().run()
if __name__=='__main__': main()
